name: Build and Push Docker image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
    - name: Build docker images
      uses: actions/checkout@v2
    
    - name: Run the local dockerfile
      run: docker build -t demo .
