name: Build and Push Docker image

on:
  push:
    branches:
      - main

jobs:
  build:    
    steps:
    - name: Build docker images
      uses: actions/checkout@v2
      run: docker build -t demo .
